SCATTER_LAYER_CONFIGS = {
    "parking_meters": {
        "marker_size": 10,
        "marker_color": "#8B008B",
        "marker_opacity": 1,
        "name": "Parkovací automaty",
        "legend_group": "Doprava",
    },
    "parking_p_r": {
        "marker_size": 10,
        "marker_color": "#2E7D32",
        "marker_opacity": 1,
        "name": "Parkoviště P+R",
        "legend_group": "Doprava",
    },
    "police_stations": {
        "marker_size": 10,
        "marker_color": "#1565C0",
        "marker_opacity": 1,
        "name": "Policejní stanice",
        "legend_group": "Bezpečnost",
    },
    "ztp_parking": {
        "marker_size": 10,
        "marker_color": "#F57C00",
        "marker_opacity": 1,
        "name": "Parkovací stání ZTP",
        "legend_group": "Doprava",
    },
    "parks": {
        "marker_size": 10,
        "marker_color": "#16a34a",
        "marker_opacity": 0.8,
        "name": "Parky a zeleň",
        "legend_group": "Prostředí",
    },
    "nextbike": {
        "marker_size": 10,
        "marker_color": "#0891b2",
        "marker_opacity": 1,
        "name": "Nextbike stanice",
        "legend_group": "Doprava",
    },
    "pid_stops": {
        "marker_size": 6,
        "marker_color": "#7c3aed",
        "marker_opacity": 0.7,
        "name": "Zastávky PID",
        "legend_group": "Doprava",
    },
}
